version: "3"
services:
   secure-coding-app:
        build: 
            context: .
        container_name: tannersgallery
#   nginx:
#       image: nginx
#        container_name: nginx
#        volumes:
#             - /etc/nginx/sites-enabled/secure-coding-app.conf:/etc/nginx/conf.d/default.conf
#        ports:
#             - 80:80
   gallerydb:
        image: postgres
        container_name: galleryDatabase
        environment:
             - POSTGRES_PASSWORD=R3nnat77
        ports:
             - 5432:5432
   wgadmindb:
      image: postgres
      container_name: WGAdminDatabase
      environment:
         - POSTGRES_PASSWORD=wgadmin
         - POSTGRES_USER=postgres
      volumes:
         - ./db-data/:/var/lib/postgresql/data/
      expose:
         - "5432"
#   app:
#      build: ../WGAdmin/
#      container_name: WGAdmin
#      ports:
#         - 3000:80

#   api:
#      build: ../WGAdminAPI/WGAdminAPI/
#      container_name: WGAdminAPI
#      depends_on:
#         - wgadmindb
#      ports:
#         - 5000:80
   swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
             - NET_ADMIN
        environment:
             - PUID=1000
             - PGID=1000
             - URL=tannersgallery.duckdns.org
             - TZ=America/Denver
             - DUCKDNSTOKEN=d7225dd0-1f2b-480e-bc9d-6e48ec2bb0f7
             - SUBDOMAINS=wildcard
             - VALIDATION=duckdns
             - STAGING=false
        volumes:
             - /etc/swag:/config
             - /etc/nginx/sites-enabled/secure-coding-app.conf:/config/nginx/site-confs/default
             - /var/repos/Secure-Coding-Project/WGAdmin/build:/WGAdmin
        ports:
             - 443:443
             - 80:80
        depends_on:
#             - nginx
             - gallerydb
             - secure-coding-app
        restart: unless-stopped
        extra_hosts:
             - host.docker.internal:host-gateway
